// SMO Design System/ui_kits/login/Wordmark.jsx
// SMO — Wordmark component
// Off-white "SMO" with a blue dot beat after it. The dot is the only ornament.

const Wordmark = ({ size = 40 }) => {
  // Tuned dot/text proportions for crisp rendering at common sizes.
  const dot = Math.max(4, Math.round(size * 0.13));
  const lift = Math.round(size * 0.07);
  return (
    <span style={{ display: 'inline-flex', alignItems: 'baseline', userSelect: 'none' }} aria-label="SMO">
      <span style={{
        fontFamily: "'Inter', ui-sans-serif, system-ui, sans-serif",
        fontWeight: 700,
        fontSize: `${size}px`,
        letterSpacing: '-0.03em',
        color: '#F5F6F8',
        lineHeight: 1,
      }}>SMO</span>
      <span style={{
        display: 'inline-block',
        width: `${dot}px`,
        height: `${dot}px`,
        borderRadius: '999px',
        background: '#2080FF',
        marginLeft: `${Math.max(3, Math.round(size * 0.1))}px`,
        transform: `translateY(-${lift}px)`,
      }} />
    </span>
  );
};

Object.assign(window, { Wordmark });

// frontend/app/components/Wordmark.vue
<script setup lang="ts">
const props = withDefaults(defineProps<{ size?: number }>(), { size: 40 })

const dotPx = computed(() => Math.max(4, Math.round(props.size * 0.13)))
const liftPx = computed(() => Math.round(props.size * 0.07))
const gapPx = computed(() => Math.max(3, Math.round(props.size * 0.1)))
</script>

<template>
  <span
    class="inline-flex items-baseline select-none"
    aria-label="SMO"
  >
    <span
      class="font-bold tracking-tight text-fg-emphasis leading-none font-sans"
      :style="{ fontSize: `${size}px` }"
    >SMO</span>
    <span
      class="inline-block rounded-full bg-action-primary"
      :style="{
        width: `${dotPx}px`,
        height: `${dotPx}px`,
        marginLeft: `${gapPx}px`,
        transform: `translateY(-${liftPx}px)`,
      }"
    />
  </span>
</template>
